on error ignore precedence over -b
microsoft/go-sqlcmd pull request #181
Opened 2023-01-05 07:42 UTC by JyotikaGargg

https://github.com/microsoft/go-sqlcmd/issues/179
When a user specifies following command :
"sqlcmd on-error.sql -b"

In on-error.sql :

:ONERROR ignore

select @@versionn

GO

select @@version

GO
Actual Output : It is exiting with error code.
Expected Output : It should run with only printing error message

2023-01-05 13:49 UTC, shueybubbles commented
pls add a test that fails without this fix

2023-01-05 13:49 UTC, shueybubbles requested changes
:clock1:

2023-01-05 13:50 UTC, apoorvdeshmukh reviewed
Can you also extend or add a testcase for the issue mentioned in PR?

2023-01-06 09:40 UTC, apoorvdeshmukh approved these changes

2023-01-06 18:09 UTC, shueybubbles approved these changes
:shipit:

2023-01-09 07:31 UTC, merged